"""Tests for ``pkm.producers.pandoc`` — the Pandoc extractor
(SPEC §7.1, §7.2).

Fixtures are generated on demand rather than committed as binary
blobs. The .docx fixture is produced by pandoc itself from a tiny
markdown seed — this is circular (we're testing pandoc) but it's
deterministic as long as pandoc's own markdown→docx output is
valid docx, which is a far weaker claim than "bytes are stable".

Tests that exercise a real subprocess require pandoc on PATH. Any
environment without pandoc will fail at discovery with a clear
``ProducerDiscoveryError``; we don't skip, because a pkm env
without pandoc is already misconfigured.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from pkm.producer import (
    Producer,
    ProducerResult,
    ProducerVersionMismatchError,
)
from pkm.producers.pandoc import (
    PandocProducer,
    installed_pandoc_version,
)


@pytest.fixture(scope="module")
def pandoc_version() -> str:
    """The pandoc version on this host, discovered once per module."""
    return installed_pandoc_version()


@pytest.fixture
def producer(pandoc_version: str) -> PandocProducer:
    return PandocProducer(expected_version=pandoc_version)


@pytest.fixture
def md_file(tmp_path: Path) -> Path:
    path = tmp_path / "hello.md"
    path.write_text(
        "# Hello\n\nThis is **bold** text with a list:\n\n"
        "- item one\n- item two\n",
        encoding="utf-8",
    )
    return path


@pytest.fixture
def txt_file(tmp_path: Path) -> Path:
    path = tmp_path / "hello.txt"
    path.write_text("Plain text, no markup.\n", encoding="utf-8")
    return path


@pytest.fixture
def html_file(tmp_path: Path) -> Path:
    path = tmp_path / "hello.html"
    path.write_text(
        "<!DOCTYPE html><html><body>"
        "<h1>Hello</h1><p>HTML <em>body</em>.</p>"
        "</body></html>",
        encoding="utf-8",
    )
    return path


@pytest.fixture
def docx_file(tmp_path: Path) -> Path:
    """A valid .docx generated by pandoc from a tiny markdown seed.
    Bootstrapping from pandoc is fine because we are testing pandoc.
    """
    seed = tmp_path / "_docx_seed.md"
    seed.write_text("# DOCX Title\n\nBody text inside docx.\n", encoding="utf-8")
    path = tmp_path / "hello.docx"
    subprocess.run(
        [
            "pandoc",
            "--from",
            "markdown",
            "--to",
            "docx",
            "-o",
            str(path),
            str(seed),
        ],
        check=True,
    )
    return path


@pytest.fixture
def corrupted_docx(tmp_path: Path) -> Path:
    path = tmp_path / "corrupted.docx"
    path.write_bytes(b"this is definitely not a real docx file, just bytes\n")
    return path


@pytest.fixture
def unsupported_file(tmp_path: Path) -> Path:
    """A .doc file (legacy binary Word) — pandoc reads only .docx,
    and .doc is deliberately absent from the extension map."""
    path = tmp_path / "legacy.doc"
    path.write_bytes(b"anything - the producer rejects by extension\n")
    return path


# --- Construction --------------------------------------------------------


def test_construction_succeeds_with_matching_version(
    pandoc_version: str,
) -> None:
    p = PandocProducer(expected_version=pandoc_version)
    assert p.name == "pandoc"
    assert p.version == pandoc_version


def test_construction_raises_on_version_mismatch(
    pandoc_version: str,
) -> None:
    wrong = "99.99.99"
    assert wrong != pandoc_version, "test setup requires a bogus version"
    with pytest.raises(ProducerVersionMismatchError) as excinfo:
        PandocProducer(expected_version=wrong)
    msg = str(excinfo.value)
    assert wrong in msg
    assert pandoc_version in msg
    assert "edit config" in msg.lower() or "install" in msg.lower()
    assert excinfo.value.expected == wrong
    assert excinfo.value.installed == pandoc_version
    assert excinfo.value.producer_name == "pandoc"


def test_pandoc_producer_satisfies_producer_protocol(
    producer: PandocProducer,
) -> None:
    assert isinstance(producer, Producer)


# --- Successful conversions ---------------------------------------------


def test_converts_markdown_to_plain(
    producer: PandocProducer, md_file: Path,
) -> None:
    result = producer.produce(md_file, "a" * 64, {})
    assert isinstance(result, ProducerResult)
    assert result.status == "success"
    assert result.content_type == "text/plain"
    assert result.content_encoding == "utf-8"
    assert result.error_message is None
    assert isinstance(result.content, bytes)
    text = result.content.decode("utf-8")
    assert "Hello" in text
    # "**bold**" markdown becomes just "bold" in plain text.
    assert "bold" in text
    assert "**bold**" not in text
    assert "item one" in text


def test_converts_txt_passthrough(
    producer: PandocProducer, txt_file: Path,
) -> None:
    result = producer.produce(txt_file, "a" * 64, {})
    assert result.status == "success"
    assert result.content is not None
    assert b"Plain text" in result.content


def test_converts_html_to_plain(
    producer: PandocProducer, html_file: Path,
) -> None:
    result = producer.produce(html_file, "a" * 64, {})
    assert result.status == "success"
    assert result.content is not None
    text = result.content.decode("utf-8")
    assert "Hello" in text
    assert "<h1>" not in text
    assert "HTML" in text


def test_converts_docx_to_plain(
    producer: PandocProducer, docx_file: Path,
) -> None:
    result = producer.produce(docx_file, "a" * 64, {})
    assert result.status == "success"
    assert result.content is not None
    text = result.content.decode("utf-8")
    assert "DOCX Title" in text
    assert "Body text inside docx" in text


# --- Failure paths ------------------------------------------------------


def test_unsupported_extension_is_recorded_as_failed(
    producer: PandocProducer, unsupported_file: Path,
) -> None:
    result = producer.produce(unsupported_file, "a" * 64, {})
    assert result.status == "failed"
    assert result.content is None
    assert result.content_type is None
    assert result.content_encoding is None
    assert result.error_message is not None
    assert ".doc" in result.error_message
    assert "supported" in result.error_message.lower()


def test_corrupted_docx_records_pandoc_error(
    producer: PandocProducer, corrupted_docx: Path,
) -> None:
    result = producer.produce(corrupted_docx, "a" * 64, {})
    assert result.status == "failed"
    assert result.content is None
    assert result.error_message is not None
    # Pandoc exits non-zero with a "couldn't unpack docx container"
    # or similar stderr message. We assert on the prefix we emit
    # plus the non-empty stderr inclusion.
    assert "pandoc exited" in result.error_message.lower()


def test_produce_never_raises_on_failure_paths(
    producer: PandocProducer,
    unsupported_file: Path,
    corrupted_docx: Path,
) -> None:
    """Invariant 2 of SPEC §7.1: produce() catches its own failures
    and returns a ``ProducerResult`` with ``status="failed"``. This
    is already covered by the two previous tests; a dedicated name
    makes the invariant grep-able."""
    for path in (unsupported_file, corrupted_docx):
        r = producer.produce(path, "a" * 64, {})
        assert r.status == "failed"
        assert r.error_message
